import { AchievementDef } from '../types';

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_task',
    title: 'First Steps',
    description: 'Complete your first task',
    emoji: '🎯',
    maxProgress: 1,
  },
  {
    id: 'five_tasks',
    title: 'Getting Going',
    description: 'Complete 5 tasks',
    emoji: '⚡',
    maxProgress: 5,
  },
  {
    id: 'twenty_five_tasks',
    title: 'Momentum',
    description: 'Complete 25 tasks',
    emoji: '🚀',
    maxProgress: 25,
  },
  {
    id: 'centurion',
    title: 'Centurion',
    description: 'Complete 100 tasks',
    emoji: '💯',
    maxProgress: 100,
  },
  {
    id: 'first_habit',
    title: 'Habit Starter',
    description: 'Create your first habit',
    emoji: '🌱',
    maxProgress: 1,
  },
  {
    id: 'streak_3',
    title: 'On a Roll',
    description: 'Maintain a 3-day streak',
    emoji: '🔥',
    maxProgress: 3,
  },
  {
    id: 'streak_7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    emoji: '💪',
    maxProgress: 7,
  },
  {
    id: 'streak_14',
    title: 'Fortnight Focus',
    description: 'Maintain a 14-day streak',
    emoji: '🏆',
    maxProgress: 14,
  },
  {
    id: 'streak_30',
    title: 'Monthly Master',
    description: '30-day streak achieved!',
    emoji: '👑',
    maxProgress: 30,
  },
  {
    id: 'five_habits',
    title: 'Habit Machine',
    description: 'Track 5 different habits',
    emoji: '🎪',
    maxProgress: 5,
  },
  {
    id: 'project_starter',
    title: 'Project Starter',
    description: 'Create your first project',
    emoji: '📂',
    maxProgress: 1,
  },
  {
    id: 'note_taker',
    title: 'Idea Collector',
    description: 'Save 10 notes',
    emoji: '💡',
    maxProgress: 10,
  },
  {
    id: 'completionist',
    title: 'Completionist',
    description: 'Check in all habits in one day',
    emoji: '✅',
    maxProgress: 1,
  },
];
